trigger:
  - master
pool:
  vmImage: ubuntu-latest
steps:
  - script: |
      echo building images
      docker build -f Dockerfile.fedora-latex-emacs -t mercur3/fedora-latex-emacs
      docker login -u mercur3 -p $DOCKER_PASSWORD
      docker push mercur3/fedora-latex-emacs
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)

