trigger:
  - master
pool:
  vmImage: ubuntu-latest
steps:
  - script: |
      echo "Building the images"
      echo "------------------------------------------------------\n"
      docker build -f Dockerfile.medium -t $MEDIUM_IMG .
      docker build -f Dockerfile.full -t $FULL_IMG .
      docker login -u mercur3 -p $DOCKER_PASSWORD
      docker push $MEDIUM_IMG
      docker push $FULL_IMG
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      MEDIUM_IMG: mercur3/fedora-latex-emacs:medium
      FULL_IMG: mercur3/fedora-latex-emacs:full

