trigger:
  - master
pool:
  vmImage: ubuntu-latest
steps:
  - script: |
      echo "Building the image"
      echo "------------------------------------------------------"
      docker build -f Dockerfile.fedora-latex-emacs -t $IMG_NAME .
      docker login -u mercur3 -p $DOCKER_PASSWORD
      docker push $IMG_NAME
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      IMG_NAME: mercur3/fedora-latex-emacs

